<form action="<?= $this->url('portal', ['action' => 'dashboard',], true) ?>" enctype="multipart/form-data" method="post">
    <div class="dashboard__form-col dashboard__form-col--fields">
        <div class="dashboard__input-group">
            <select class="dashboard__input-field dashboard__input-field--select"
                    name="faqId">
                <?php foreach ($this->faqTable as $item) :
                    $item = (array) $item; ?>
                    <option value="<?= $item['faqId'] ?>"><?= $item['faqName'] ?></option>
                <?php endforeach; ?>
            </select>
            <label class="dashboard__input-label">Faq Name</label>
        </div>
        <div class="dashboard__input-group">
            <input class="dashboard__input-field dashboard__input-field--text" type="text"
                   name="title"/>
            <label class="dashboard__input-label">Title</label>
        </div>
        <div class="dashboard__input-group">
            <textarea class="dashboard__input-field dashboard__input-field--textarea" name="description"></textarea>
            <label class="dashboard__input-label">Description</label>
        </div>
        <div class="dashboard__divider"></div>
        <div class="dashboard__actions" data-panel="faq" data-action="faq">
            <input type="hidden" name="process" value="add-faq-details"/>
            <input class="dashboard__button dashboard__button--secondary js-dialog-close" type="button" value="Cancel"/>
            <input class="dashboard__button dashboard__button--primary" type="submit" value="Confirm"/>
        </div>
    </div>
</form>