<nav class="navigation" role="navigation">
    <div class="navigation__bar">
        <div class="navigation__item navigation__item--logo">
            <a href="<?= $this->url('home') ?>"><img src="/assets/images/logo.png"/></a>
        </div>
        <div class="navigation__item navigation__item--title">
            <a href="<?= $this->url('home') ?>"><span>Opermitcare</span></a>
        </div>
        <ul class="navigation__item navigation__item--services">
            <li><a href="#">Program & Services</a></li>
            <li><a href="#">Find a Form</a></li>
            <li><a href="#">Support</a></li>
        </ul>
        <ul class="navigation__item navigation__item--info">
            <li><a href="#">About Us</a></li>
            <li><a href="<?= $this->url('login') ?>">Login</a></li>
        </ul>
    </div>
</nav>