<html>
<head>
    <style>
        .statement-of-account {
            float: left;
            width: 100%;
            font-size: 12px;
        }
        .statement-of-account__header {
            float: left;
            width: 100%;
            text-align: left;
        }
        .statement-of-account__title--1 {
            font-size: 16px;
        }
        .statement-of-account__title--2 {
            font-size: 14px;
        }
        .statement-of-account__title--3 {
            font-size: 12px;
        }
        .statement-of-account__heading {
            border-bottom: 2px solid #000000;
            padding: 0 10px;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <div class="statement-of-account">
        <div class="statement-of-account__header">
            <div class="statement-of-account__title">
                <span class="statement-of-account__title--1">REPUBLIC OF THE PHILIPPINES</span>
                <span class="statement-of-account__title--2">CITY GOVERNMENT OF LAS PIÑAS</span>
                <span class="statement-of-account__title--3">Opermitcare Special Permit</span>
            </div>
            <div class="statement-of-account__heading">Statement of Account</div>
        </div>
    </div>
</body>
</html>