<?php
$permitId = sprintf('%s%06d', date("Y", strtotime($this->data['dateCreated'])), $this->data['ticketId']);
?>
<form action="<?= $this->url('portal', ['action' => 'dashboard',], true) ?>" enctype="multipart/form-data" method="post">
    <div class="dashboard__form-col dashboard__form-col--fields">
        <div class="dashboard__input-group">
            <input class="dashboard__input-field dashboard__input-field--text" type="text" value="<?= $permitId ?>" readonly>
            <label class="dashboard__input-label">Permit Id</label>
        </div>
        <div class="dashboard__input-group">
            <select class="dashboard__input-field dashboard__input-field--select"
                    name="permitStatusId">
                <?php foreach ($this->permitStatusTable as $item) :
                    $item = (array) $item;
                    $isActive = $item['permitStatusId'] === $this->data['permitStatusId'] ? ' selected' : ''; ?>
                    <option value="<?= $item['permitStatusId'] ?>"<?=$isActive?>><?= ucwords($item['permitStatusName']) ?></option>
                <?php endforeach; ?>
            </select>
            <label class="dashboard__input-label">Permit Status</label>
        </div>
        <div class="dashboard__divider"></div>
        <div class="dashboard__actions" data-panel="permit" data-action="permit">
            <input type="hidden" name="permitId" value="<?= $this->data['permitId'] ?>"/>
            <input type="hidden" name="process" value="update-permit"/>
            <input class="dashboard__button dashboard__button--secondary js-dialog-close" type="button" value="Cancel"/>
            <input class="dashboard__button dashboard__button--primary" type="submit" value="Confirm"/>
        </div>
    </div>
</form>