<?php
$layoutVariables = $this->layout()->getVariables('layoutVariables');
$sessionDetails = $this->sessionDetails;
$pageKey = array_search($this->tabKey, array_column($this->pages, 'action'));
$page = $this->pages[$pageKey];
$requiredColumns = [
    'user' => ['userId', 'userName', 'email'],
    'faq' => ['faqId', 'faqName', 'active'],
    'faq-details' => ['faqDetailsId', 'title', 'faqName'],
    'problem-type' => ['problemTypeId', 'problemTypeName', 'active'],
    'ticket' => ['ticketId', 'problemTypeName', 'ticketStatusName', 'dateCreated'],
    'permit' => ['permitId', 'businessEntityType', 'permitStatusName', 'dateCreated'],
];
?>
<?php if ($this->alertMessage) : ?>
    <div class="alert<?= $this->alertClass ?>">
        <span><?= $this->alertMessage ?></span>
        <a class="alert__button js-alert-close">&times;</a>
    </div>
<?php endif; ?>
<div class="dashboard__panel-header">
    <h1><?= $page['title'] ?></h1>
    <p>
        <?= $page['description'] ?>
    </p>
</div>
<div class="dashboard__panel-body">
    <?php foreach ($this->dataTables as $category => $row) :
        $tableRow = (array) $row;
        $fistItem = (array) $tableRow[0];
        $tableHeads = array_keys($fistItem);
        $required = !empty($requiredColumns[$category]) ? $requiredColumns[$category] : []; ?>
        <div class="dashboard__divider"></div>
        <h4><?= ucwords(preg_replace('/([a-z0-9])([A-Z])/', "$1 $2", str_replace('-', ' ', $category))) ?> Table</h4>
        <table id="dt-<?= $category ?>"
               class="dashboard__data-table display responsive stripe row-border order-column js-data-table"
               data-table-name="<?= $category ?>" style="width:100%">
            <thead>
            <tr>
                <?php foreach ($required as $columnKey) : ?>
                    <th><?= ucwords(preg_replace('/([a-z0-9])([A-Z])/', "$1 $2", $columnKey)) ?></th>
                <?php endforeach; ?>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($tableRow as $rowItem) :
                $tdValues = (array) $rowItem;
                $dateCreated = $tdValues['dateCreated'];
                $required = !empty($requiredColumns[$category]) ? $requiredColumns[$category] : [];
                ?>
                <tr>
                    <?php foreach ($required as $columnKey) :
                        $value = $tdValues[$columnKey];

                        if ($columnKey === 'active') {
                            $value = $tdValues[$columnKey] === 1 ? 'True' : 'False';
                        }

                        if (in_array($columnKey, ['permitId', 'ticketId'])) {
                            $value = sprintf('%s%06d', date("Y", strtotime($dateCreated)), $tdValues[$columnKey]);
                        }

                        if (in_array($columnKey, ['ticketStatusName', 'permitStatusName'])) {
                            $value = ucwords($tdValues[$columnKey]);
                        } ?>
                        <td><?= $value ?></td>
                    <?php endforeach; ?>
                    <td>
                        <input class="dashboard__data-table-button" type="button" value="Edit"/>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endforeach; ?>
</div>
