<?php

$layoutVariables = $this->layout()->getVariables('layoutVariables');
$sessionDetails = $this->sessionDetails;
$permitStatusKey = array_search('faq', array_column($this->pages, 'action'));
$page = $this->pages[$permitStatusKey];
?>

<div class="dashboard">
    <div class="dashboard__jumbotron">
        <div class="dashboard__wrapper">
            <h1><?= $page['title']; ?></h1>
            <p><?= $page['description']; ?></p>
        </div>
    </div>
    <div class="dashboard__section">
        <div class="dashboard__wrapper dashboard__wrapper--section">
            <h1>FAQ Category</h1>
            <table id="data-table" class="dashboard__data-table display">
                <thead>
                    <tr>
                        <th>Category</th>
                        <th width="10%">Active</th>
                        <th width="30%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->faq as $faq) :
                        $item = (array) $faq;
                        $action = $item['active'] ? 'Disable' : 'Enable';
                    ?>
                    <tr data-id="<?= $item['faqId'] ?>">
                        <td><?= $item['faqName'] ?></td>
                        <td align="center"><?= $item['active'] ? 'Yes' : 'No' ?></td>
                        <td align="center">
                            <input type="button" value="Edit"/>
                            <input type="button" value="<?= $action ?>"/>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>