<?php
$layoutVariables = $this->layout()->getVariables('layoutVariables');
?>
<?php if ($this->alertMessage) : ?>
    <div class="alert<?= $this->alertClass ?>">
        <span><?= $this->alertMessage ?></span>
        <a class="alert__button js-alert-close">&times;</a>
    </div>
<?php endif; ?>
<div class="dashboard__panel-header">
    <h1><?= $this->title ?></h1>
    <p>
        <?= $this->description ?>
    </p>
</div>
<div class="dashboard__panel-body dashboard__panel-body--overview">
    <div class="dashboard__panel-card-wrapper dashboard__panel-card-wrapper--left">
        <div class="dashboard__panel-card dashboard__panel-card--welcome">
            <p>Welcome back,</p>
            <h3><?= sprintf('%s (@%s)', $this->sessionDetails['user']['firstName'], $this->sessionDetails['user']['userName']) ?></h3>
        </div>
        <div class="dashboard__divider"></div>
        <?php foreach ($this->overviewDetails['ticketStatus'] as  $ticketStatusKey => $ticketStatus) : ?>
            <div class="dashboard__panel-card">
                <h1>Total <?= ucwords($ticketStatus['ticketStatusName']) ?> Tickets</h1>
                <div class="dashboard__panel-card-count"><?= $ticketStatus['count'] ?></div>
            </div>
        <?php endforeach; ?>
        <div class="dashboard__divider"></div>
        <?php foreach ($this->overviewDetails['permitStatus'] as  $permitStatusKey => $permitStatus) : ?>
            <div class="dashboard__panel-card">
                <h1>Total <?= ucwords($permitStatus['permitStatusName']) ?> Permits</h1>
                <div class="dashboard__panel-card-count"><?= $permitStatus['count'] ?></div>
            </div>
        <?php endforeach; ?>
        <div class="dashboard__divider"></div>
        <?php foreach ($this->overviewDetails['problemType'] as  $problemTypeKey => $problemType) : ?>
            <div class="dashboard__panel-card">
                <h1>Total <?= ucwords($problemType['problemTypeName']) ?> Issues</h1>
                <div class="dashboard__panel-card-count"><?= $problemType['count'] ?></div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="dashboard__panel-card-wrapper dashboard__panel-card-wrapper--right">
    </div>
</div>