<?php
$layoutVariables = $this->layout()->getVariables('layoutVariables');
?>
<?php if ($this->alertMessage) : ?>
    <div class="alert<?= $this->alertClass ?>">
        <span><?= $this->alertMessage ?></span>
        <a class="alert__button js-alert-close">&times;</a>
    </div>
<?php endif; ?>
<div class="dashboard__panel-header">

</div>
<div class="dashboard__panel-body dashboard__panel-body--overview">
    <div class="dashboard__panel-card dashboard__panel-card--welcome">
        <p>Welcome back,</p>
        <h3><?= sprintf('%s (@%s)', $this->sessionDetails['user']['firstName'], $this->sessionDetails['user']['userName']) ?></h3>

        <h1><?= $this->title ?></h1>
        <p>
            <?= $this->description ?>
        </p>
    </div>
    <div class="dashboard__divider"></div>
    <?php foreach ($this->overview['ticketStatus'] as  $ticketStatusKey => $ticketStatus) : ?>
        <div class="dashboard__panel-card">
            <h1>Total <?= ucwords($ticketStatus['ticketStatusName']) ?> Ticket (s)</h1>
            <div class="dashboard__panel-card-count"><?= $ticketStatus['count'] ?></div>
        </div>
    <?php endforeach; ?>
    <div class="dashboard__divider"></div>
    <?php foreach ($this->overview['permitStatus'] as  $permitStatusKey => $permitStatus) : ?>
        <div class="dashboard__panel-card">
            <h1>Total <?= ucwords($permitStatus['permitStatusName']) ?> Permit (s)</h1>
            <div class="dashboard__panel-card-count"><?= $permitStatus['count'] ?></div>
        </div>
    <?php endforeach; ?>
    <div class="dashboard__divider"></div>
    <?php foreach ($this->overview['problemType'] as  $problemTypeKey => $problemType) : ?>
        <div class="dashboard__panel-card">
            <h1>Total <?= ucwords($problemType['problemTypeName']) ?> Issue (s)</h1>
            <div class="dashboard__panel-card-count"><?= $problemType['count'] ?></div>
        </div>
    <?php endforeach; ?>
</div>