<div class="dashboard__panel-header">
    <h1><?= $this->title ?></h1>
    <p>
        <?= $this->description ?>
    </p>
</div>
<div class="dashboard__panel-body dashboard__form--reports">
    <form action="<?= $this->url('portal', ['action' => 'dashboard',], true) ?>" enctype="multipart/form-data" method="post">
        <div class="dashboard__actions">
            <div class="dashboard__form-col dashboard__form-col--date">
                <div class="dashboard__input-group">
                    <input class="dashboard__input-field dashboard__input-field--text" id="start-date" name="from"/>
                    <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M22 14V12C22 11.161 22 10.4153 21.9871 9.75H2.0129C2 10.4153 2 11.161 2 12V14C2 17.7712 2 19.6569 3.17157 20.8284C4.34315 22 6.22876 22 10 22H14C17.7712 22 19.6569 22 20.8284 20.8284C22 19.6569 22 17.7712 22 14Z"/>
                        <path d="M7.75 2.5C7.75 2.08579 7.41421 1.75 7 1.75C6.58579 1.75 6.25 2.08579 6.25 2.5V4.07926C4.81067 4.19451 3.86577 4.47737 3.17157 5.17157C2.47737 5.86577 2.19451 6.81067 2.07926 8.25H21.9207C21.8055 6.81067 21.5226 5.86577 20.8284 5.17157C20.1342 4.47737 19.1893 4.19451 17.75 4.07926V2.5C17.75 2.08579 17.4142 1.75 17 1.75C16.5858 1.75 16.25 2.08579 16.25 2.5V4.0129C15.5847 4 14.839 4 14 4H10C9.16097 4 8.41527 4 7.75 4.0129V2.5Z"/>
                    </svg>
                    <label class="dashboard__input-label">Start Date</label>
                </div>
            </div>
            <div class="dashboard__form-col dashboard__form-col--date">
                <div class="dashboard__input-group dashboard__input-group--end-date">
                    <input class="dashboard__input-field dashboard__input-field--text" id="end-date" name="to"/>
                    <svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M22 14V12C22 11.161 22 10.4153 21.9871 9.75H2.0129C2 10.4153 2 11.161 2 12V14C2 17.7712 2 19.6569 3.17157 20.8284C4.34315 22 6.22876 22 10 22H14C17.7712 22 19.6569 22 20.8284 20.8284C22 19.6569 22 17.7712 22 14Z"/>
                        <path d="M7.75 2.5C7.75 2.08579 7.41421 1.75 7 1.75C6.58579 1.75 6.25 2.08579 6.25 2.5V4.07926C4.81067 4.19451 3.86577 4.47737 3.17157 5.17157C2.47737 5.86577 2.19451 6.81067 2.07926 8.25H21.9207C21.8055 6.81067 21.5226 5.86577 20.8284 5.17157C20.1342 4.47737 19.1893 4.19451 17.75 4.07926V2.5C17.75 2.08579 17.4142 1.75 17 1.75C16.5858 1.75 16.25 2.08579 16.25 2.5V4.0129C15.5847 4 14.839 4 14 4H10C9.16097 4 8.41527 4 7.75 4.0129V2.5Z"/>
                    </svg>
                    <label class="dashboard__input-label">End Date</label>
                </div>
            </div>
            <input type="hidden" name="process" value="get-report"/>
            <input class="dashboard__button dashboard__button--primary" type="submit" value="Filter"/>
            <input class="dashboard__button dashboard__button--primary js-print" type="button" value="Print"
                   data-module="admin"
                   data-file="report"/>
        </div>
    </form>
    <div class="dashboard__divider"></div>
    <div class="dashboard__statement" id="statement-of-account" style="max-width: 800px">
        <table class="statement-of-account__table">
            <tbody>
            <tr>
                <td colspan="8">
                    <strong>REPUBLIC OF THE PHILIPPINES</strong><br/>
                    CITY GOVERNMENT OF LAS PIÑAS<br/>
                    Opermitcare Report
                </td>
            </tr>
            <tr>
                <td colspan="8" class="statement-of-account__table-space"></td>
            </tr>
            <?php if (!empty($this->report['from']) && !empty($this->report['to'])) : ?>
            <tr>
                <td colspan="8">
                    Report Date: <?= date("d M Y", strtotime($this->report['from'])) ?> to <?= date("d M Y", strtotime($this->report['to'])) ?><br/>
                </td>
            </tr>
            <?php else : ?>
                <tr>
                    <td colspan="8">
                        Report Date: All Time<br/>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td colspan="8" class="statement-of-account__title"><span>Report</span></td>
            </tr>
            <tr>
                <td colspan="8" class="statement-of-account__table-space"></td>
            </tr>
            <tr>
                <td colspan="7" class="statement-of-account__table-summary-title"><strong>Ticket Status</strong></td>
                <td colspan="1" class="statement-of-account__table-summary-title"><strong>Count</strong></td>
            </tr>
            <?php foreach ($this->report['ticketStatus'] as $ticketStatus) : ?>
                <tr>
                    <td colspan="7"
                        class="statement-of-account__table-summary-label"><?= ucwords($ticketStatus['ticketStatusName']); ?></td>
                    <td colspan="1" class="statement-of-account__table-summary-value"><?= $ticketStatus['count']; ?></td>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($this->report['ticketStatus'])) :?>
                <tr>
                    <td colspan="8" class="statement-of-account__table-summary-label">No Data</td>
                </tr>
            <?php endif; ?>
            <tr>
                <td colspan="8" class="statement-of-account__table-space"></td>
            </tr>
            <tr>
                <td colspan="7" class="statement-of-account__table-summary-title"><strong>Permit Status</strong></td>
                <td colspan="1" class="statement-of-account__table-summary-title"><strong>Count</strong></td>
            </tr>
            <?php foreach ($this->report['permitStatus'] as $permitStatus) : ?>
                <tr>
                    <td colspan="7"
                        class="statement-of-account__table-summary-label"><?= ucwords($permitStatus['permitStatusName']); ?></td>
                    <td colspan="1" class="statement-of-account__table-summary-value"><?= $permitStatus['count']; ?></td>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($this->report['permitStatus'])) :?>
                <tr>
                    <td colspan="8" class="statement-of-account__table-summary-label">No Data</td>
                </tr>
            <?php endif; ?>
            <tr>
                <td colspan="8" class="statement-of-account__table-space"></td>
            </tr>
            <tr>
                <td colspan="7" class="statement-of-account__table-summary-title"><strong>Problem Type</strong></td>
                <td colspan="1" class="statement-of-account__table-summary-title"><strong>Count</strong></td>
            </tr>
            <?php foreach ($this->report['problemType'] as $problemType) : ?>
                <tr>
                    <td colspan="7"
                        class="statement-of-account__table-summary-label"><?= ucwords($problemType['problemTypeName']); ?></td>
                    <td colspan="1" class="statement-of-account__table-summary-value"><?= $problemType['count']; ?></td>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($this->report['problemType'])) :?>
                <tr>
                    <td colspan="8" class="statement-of-account__table-summary-label">No Data</td>
                </tr>
            <?php endif; ?>
            <tr>
                <td colspan="8" class="statement-of-account__table-space"></td>
            </tr>
            <tr>
                <td colspan="2" class="statement-of-account__table-summary-title"><strong>Employee Id</strong></td>
                <td colspan="4" class="statement-of-account__table-summary-title"><strong>Agent Name</strong></td>
                <td colspan="2" class="statement-of-account__table-summary-title"><strong>Total Permits Assessed</strong></td>
            </tr>
            <?php foreach ($this->report['assessedPermitsList'] as $assessedPermits) : ?>
                <tr>
                    <td colspan="2" class="statement-of-account__table-summary-value"><?= $assessedPermits['userId']; ?></td>
                    <td colspan="4"
                        class="statement-of-account__table-summary-label"><?= ucwords($assessedPermits['firstName']) . ' ' . ucwords($assessedPermits['lastName']); ?></td>
                    <td colspan="2" class="statement-of-account__table-summary-value"><?= $assessedPermits['count']; ?></td>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($this->report['assessedPermitsList'])) :?>
                <tr>
                    <td colspan="8" class="statement-of-account__table-summary-label">No Data</td>
                </tr>
            <?php endif; ?>
            <tr>
                <td colspan="8" class="statement-of-account__table-space"></td>
            </tr>
            <tr>
                <td colspan="8" class="statement-of-account__table-space"></td>
            </tr>
            <tr>
                <td colspan="4">
                    <div class="statement-of-account__table-label">Generated By</div>
                    <div class="statement-of-account__table-value">
                        <strong><?= sprintf('%s %s', $this->sessionDetails['user']['firstName'], $this->sessionDetails['user']['lastName']) ?></strong>
                    </div>
                </td>
                <td colspan="4">
                    <div class="statement-of-account__table-label">Approved By</div>
                    <div class="statement-of-account__table-value">
                        <strong>Chief BPLO</strong>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="8" class="statement-of-account__table-space">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="8">
                    <div class="statement-of-account__table-label">Note</div>
                    <div class="statement-of-account__table-value">This report is online system-generated; no signature is required.</div>
                </td>
            </tr>
            <tr>
                <td colspan="8" class="statement-of-account__table-space">&nbsp;</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>