<?php

$layoutVariables = $this->layout()->getVariables('layoutVariables');
$sessionDetails = $this->sessionDetails;
$permitStatusKey = array_search('setting', array_column($this->pages, 'action'));
$page = $this->pages[$permitStatusKey];
?>

<div class="dashboard">
    <div class="dashboard__jumbotron">
        <div class="dashboard__wrapper">
            <h1><?= $page['title']; ?></h1>
            <p><?= $page['description']; ?></p>
        </div>
    </div>
    <div class="dashboard__section">
        <div class="dashboard__wrapper dashboard__wrapper--section">
        </div>
    </div>
</div>