<?php
$permitStatusKey = array_search(2, array_column($this->permitStatus, 'id'));
$permitStatus = $this->permitStatus[$permitStatusKey];
$sessionDetails = $this->sessionDetails;
$userId = $sessionDetails['user']['userId'];
$permits = $this->permits ?: [];
$countPermits = count($permits);
$isOverviewActive = $this->activeTabAction === 'overview' ? ' active' : '';
$isAssessActive = $this->activeTabAction === 'assess' ? ' active' : '';
?>

<?php if ($countPermits) : ?>
    <?php foreach ($permits as $permitNo => $permit) :
        $isActive = $this->activePanel === 'permit-' . $permit['permitId'] ? ' active' : ''; ?>
        <div class="dashboard__panel<?= $isActive ?>" data-panel="permit-<?= $permit['permitId'] ?>"
             data-permit-id="<?= $permit['permitId'] ?>">
            <div class="dashboard__panel-breadcrumbs">
                <span class="js-see-panel" data-panel="my-permit">My Special Permit (s)</span>
            </div>
            <?php if ($this->alertMessage) : ?>
                <div class="alert<?= $this->alertClass ?>">
                    <span><?= $this->alertMessage ?></span>
                    <a class="button">&times;</a>
                </div>
            <?php endif; ?>
            <div class="dashboard__panel-header">
                <h1>Permit</h1>
                <div class="dashboard__permit-status dashboard__permit-status--<?= strtolower($permit['permitStatusName']) ?>">
                    <?= $permit['permitStatusName'] ?>
                </div>
                <h4>Application no. <?= $permitNo ?></h4>
            </div>
            <div class="dashboard__tab-action">
                <div class="dashboard__tab<?= $isOverviewActive; ?>" data-tab="overview">Overview</div>
                <div class="dashboard__tab<?= $isAssessActive; ?>" data-tab="assess">Assess</div>
            </div>
            <div class="dashboard__tab-content<?= $isOverviewActive; ?>" data-tab="overview">
                <div class="dashboard__permit-details">
                    <?= $this->partial('partial/permit-details', [
                        'permit' => $permit,
                        'permitStatus' => $permitStatus,
                    ]); ?>
                </div>
                <div class="dashboard__permit-date-created">
                    <h4>Created</h4>
                    <span><?= date("d M Y", strtotime($permit['dateCreated'])) ?></span>
                </div>
                <div class="dashboard__permit-agent">
                    <h4>Recent Agent</h4>
                    <?php if (!empty($permit['agentId'])) : ?>
                        <span class="dashboard__permit-agent--name"><?= $permit['agentId']['firstName'] . ' ' . $permit['agentId']['lastName']; ?></span>
                        <span class="dashboard__permit-agent--email"><?= $permit['agentId']['email']; ?></span>
                    <?php else: ?>
                        <div class="dashboard__permit-agent">
                            <span class="dashboard__permit-agent--name">None</span>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="dashboard__tab-content<?= $isAssessActive; ?>" data-tab="assess">
                <?= $this->partial('partial/permit-assess', [
                    'responseData' => $this->responseData,
                    'permit' => $permit,
                    'permitStatus' => $permitStatus,
                ]); ?>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
