<?php
$permit = $this->permit;
$mayorsFee = [
    'Tiange Tenant' => 3000,
    'Exhibit' => 3000,
    'Operator' => 8000,
];
$licenceFee = $permit['capital'] < 999999 ? 650 : $permit['capital'] * 0.001;
$garbageFee = $permit['area'] <= 20 ? 500 : ($permit['area'] - 20) * 5;
$zoningFee = $permit['area'] <= 20 ? 300 : ($permit['area'] - 20) * 5;
?>
<form action="<?= $this->url('portal', ['action' => 'dashboard',], true) ?>" method="post">
    <div class="dashboard__form">
        <div class="dashboard__input-group">
            <label class="dashboard__dropdown">
                <div class="dashboard__dropdown-button">
                    <div class="dashboard__input-field dashboard__input-field--text"><span></span></div>
                </div>
                <input class="dashboard__dropdown-input" type="checkbox"/>
                <ul class="dashboard__dropdown-menu js-dropdown-id" data-name="mayorsFee">
                    <?php foreach ($mayorsFee as $feeName => $fee) : ?>
                        <li data-id="<?= $fee ?>">Special Permit - <?= $feeName ?>: <?= $fee ?></li>
                    <?php endforeach; ?>
                </ul>
            </label>
            <input class="dashboard__input-field"
                   type="hidden"
                   name="mayorsFee"
                   value="<?= $formData['mayorsFee']; ?>"/>
            <label class="dashboard__input-label">Mayor's Fee (if Any)</label>
        </div>
        <div class="dashboard__input-group">
            <input class="dashboard__input-field dashboard__input-field--text"
                   type="number"
                   min="650"
                   name="licenceFee"
                   value="<?= $licenceFee; ?>"
                   readonly/>
            <label class="dashboard__input-label">Licence Fee</label>
        </div>
        <div class="dashboard__input-group">
            <input class="dashboard__input-field dashboard__input-field--text"
                   type="number"
                   min="1"
                   name="area"
                   value="<?= $garbageFee; ?>"/>
            <label class="dashboard__input-label">Garbage Fee</label>
        </div>
        <div class="dashboard__input-group">
            <input class="dashboard__input-field dashboard__input-field--text"
                   type="number"
                   min="1"
                   name="area"
                   value="<?= $zoningFee; ?>"/>
            <label class="dashboard__input-label">Zoning Fee</label>
        </div>
        <div class="dashboard__input-group">
            <input class="dashboard__input-field dashboard__input-field--text"
                   type="text"
                   name="monthlyRent"
                   value="100"/>
            <label class="dashboard__input-label">Processing Fee</label>
        </div>
    </div>
    <div class="dashboard__divider"></div>
    <div class="dashboard__actions">
        <input type="hidden" name="process" value="assess-permit"/>
        <input class="dashboard__button dashboard__button--primary" type="submit" value="Assess"/>
    </div>
</form>