<?php
$problemTypeKey = array_search(2, array_column($this->problemType, 'id'));
$problemType = $this->problemType[$problemTypeKey];
$sessionDetails = $this->sessionDetails;
$userId = $sessionDetails['user']['userId'];
$tickets = $this->tickets ?: [];
$countTickets = count($tickets);
?>

<?php if ($countTickets) : ?>
    <?php foreach ($tickets as $ticketNo => $ticket) :
        $countReplies = count($ticket['replies']);
        $recentAgents = []; ?>
        <div class="dashboard__panel" data-panel="ticket-<?= $ticket['ticketId'] ?>"
             data-ticket-id="<?= $ticket['ticketId'] ?>">
            <div class="dashboard__panel-breadcrumbs">
                <span class="js-see-panel" data-panel="my-ticket">My Ticket (s)</span>
            </div>
            <div class="dashboard__panel-header">
                <h1>Ticket</h1>
                <div class="dashboard__ticket-status dashboard__ticket-status--<?= strtolower($ticket['ticketStatusName']) ?>">
                    <?= $ticket['ticketStatusName'] ?>
                </div>
                <h4>Ticket no. <?= $ticketNo ?></h4>
            </div>
            <div class="dashboard__tab-action">
                <div class="dashboard__tab active" data-tab="overview">Overview</div>
                <div class="dashboard__tab" data-tab="replies">Replies</div>
            </div>
            <div class="dashboard__tab-content active" data-tab="overview">
                <div class="dashboard__ticket-details">
                    <h1>
                        <svg viewBox="5.5 3 15 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M15.5 5H10.5C8.29086 5 6.5 6.79086 6.5 9V15C6.5 17.2091 8.29086 19 10.5 19H15.5C17.7091 19 19.5 17.2091 19.5 15V9C19.5 6.79086 17.7091 5 15.5 5Z"
                                  stroke="#000000" stroke-width="1" stroke-linecap="round"
                                  stroke-linejoin="round"></path>
                            <path d="M16 9.75C16.4142 9.75 16.75 9.41421 16.75 9C16.75 8.58579 16.4142 8.25 16 8.25V9.75ZM10 8.25C9.58579 8.25 9.25 8.58579 9.25 9C9.25 9.41421 9.58579 9.75 10 9.75V8.25ZM16 12.75C16.4142 12.75 16.75 12.4142 16.75 12C16.75 11.5858 16.4142 11.25 16 11.25V12.75ZM10 11.25C9.58579 11.25 9.25 11.5858 9.25 12C9.25 12.4142 9.58579 12.75 10 12.75V11.25ZM13 15.75C13.4142 15.75 13.75 15.4142 13.75 15C13.75 14.5858 13.4142 14.25 13 14.25V15.75ZM10 14.25C9.58579 14.25 9.25 14.5858 9.25 15C9.25 15.4142 9.58579 15.75 10 15.75V14.25ZM16 8.25H10V9.75H16V8.25ZM16 11.25H10V12.75H16V11.25ZM13 14.25H10V15.75H13V14.25Z"
                                  fill="#000000"></path>
                        </svg>
                        <span><?= $problemType['name']; ?></span>
                    </h1>
                    <div class="dashboard__ticket-detail">
                        <div class="dashboard__ticket-detail--label">Title</div>
                        <div class="dashboard__ticket-detail--value"><?= $ticket['title'] ?></div>
                    </div>
                    <div class="dashboard__ticket-detail">
                        <div class="dashboard__ticket-detail--label">Description</div>
                        <div class="dashboard__ticket-detail--value"><?= $ticket['description'] ?></div>
                    </div>
                </div>
                <div class="dashboard__ticket-date-created">
                    <h4>Created</h4>
                    <span><?= date("d M Y", strtotime($ticket['dateCreated'])) ?></span>
                </div>
                <div class="dashboard__ticket-agents">
                    <?php foreach ($ticket['replies'] as $reply) : ?>
                        <?php if ($reply['sender']['userTypeId'] === 3
                            && !in_array($reply['sender']['userId'], $recentAgents)) :
                            $recentAgents[$reply['sender']['userId']] = $reply['sender']; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <h4>Recent Agent (s)</h4>
                    <?php if (count($recentAgents)) : ?>
                        <?php foreach ($recentAgents as $agent) : ?>
                            <div class="dashboard__ticket-agent">
                                <span class="dashboard__ticket-agent--name"><?= $agent['firstName'] . $agent['lastName']; ?></span>
                                <span class="dashboard__ticket-agent--email"><?= $agent['email'] ?></span>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="dashboard__ticket-agent">
                            <span class="dashboard__ticket-agent--name">None</span>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="dashboard__divider"></div>
                <div class="dashboard__actions">
                    <input class="dashboard__button dashboard__button--primary js-ticket-action" type="button" value="Close"/>
                </div>
            </div>
            <div class="dashboard__tab-content" data-tab="replies">
                <?php if ($countReplies) :
                    $dateList = [];
                    ?>
                    <div class="dashboard__reply-collection">
                        <?php foreach ($ticket['replies'] as $reply) :
                            $isYou = $reply['sender']['userId'] === $userId;
                            $class = $isYou ? '--right' : '--left';
                            $displayName = $isYou ? 'You' : $reply['sender']['firstName'];
                            $date = date("d M Y", strtotime($reply['dateCreated'])); ?>
                            <?php if (!in_array($date, $dateList)) :
                            $dateList[] = $date; ?>
                            <div class="dashboard__reply">
                                <div class="dashboard__reply-date"><?= $date ?></div>
                            </div>
                        <?php endif; ?>
                            <div class="dashboard__reply dashboard__reply<?= $class ?>">
                                <div class="dashboard__reply-sender">
                                    <span class="dashboard__reply-sender--type"><?= $reply['userTypeId']['userTypeName']; ?></span>
                                    <span class="dashboard__reply-sender--name"><?= $displayName ?></span>
                                </div>
                                <div class="dashboard__reply-bubble">
                                    <?= $reply['message'] ?>
                                </div>
                                <div class="dashboard__reply-time"><?= date("H:i a",
                                                                            strtotime($reply['dateCreated'])) ?></div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php else: ?>
                    <div class="dashboard__reply-collection">
                        <div class="dashboard__reply-empty">No replies yet</div>
                    </div>
                <?php endif; ?>
                <div class="dashboard__reply-submit">
                    <input class="dashboard__reply-input" type="text"/>
                    <input class="dashboard__button dashboard__button--primary" type="button" value="Reply"/>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
