<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$layoutVariables = $this->layout()->getVariable('layoutVariables');
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Opermitcare')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
             ->appendName('viewport', 'width=device-width, initial-scale=1.0')
             ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
                            'rel' => 'shortcut icon',
                            'type' => 'image/vnd.microsoft.icon',
                            'href' => $this->basePath() . 'assets/images/logo.png',
                        ])
             ->prependStylesheet($this->basePath('assets/css/app.css'));
    ?>
    <?= $this->headScript() ?>
</head>
<body>
<header role="banner">
    <?= $this->partial('partial/navigation', $layoutVariables) ?>
</header>
<section class="content">
    <?= $this->content ?>
</section>
<footer role="group">
    <?= $this->partial('partial/footer', $layoutVariables) ?>
</footer>
<?= $this->inlineScript()
         ->prependFile($this->basePath('assets/js/app.js')); ?>
</body>
</html>