<div class="dashboard__panel-breadcrumbs">
    <span class="js-see-panel" data-panel="my-ticket">My Ticket (s)</span>
</div>
<?php if ($this->alertMessage) : ?>
    <div class="alert<?= $this->alertClass ?>">
        <span><?= $this->alertMessage ?></span>
        <a class="button">&times;</a>
    </div>
<?php endif; ?>
<div class="dashboard__panel-header">
    <h1><?= $this->title ?></h1>
    <p>
        After you submit your question, we will reply during working hours from 8:00am to 5:00pm.
        Please pay attention to the ticket message actively. If you have any doubts about our verification
        results, please reply to us again for verification. We will also give you a reply during work hours.
        If you problem needs technical personnel to verify the situation, it will take more time. We will
        inform you in the ticket reply. Please be patient.
    </p>
</div>
<form action="<?= $this->url('portal', ['action' => 'dashboard',], true) ?>" enctype="multipart/form-data" method="post">
    <div class="dashboard__form">
        <div class="dashboard__input-group">
            <label class="dashboard__dropdown">
                <div class="dashboard__dropdown-button">
                    <div class="dashboard__input-field dashboard__input-field--text"><span></span></div>
                </div>
                <input class="dashboard__dropdown-input" type="checkbox"/>
                <ul class="dashboard__dropdown-menu js-dropdown-id" data-name="problemTypeId">
                    <?php foreach ($this->problemType as $problemType) : ?>
                        <li data-id="<?= $problemType['id'] ?>"><?= $problemType['name']; ?></li>
                    <?php endforeach; ?>
                </ul>
            </label>
            <input class="dashboard__input-field" type="hidden" name="problemTypeId"/>
            <label class="dashboard__input-label">Problem Type</label>
        </div>
        <div class="dashboard__input-group">
            <input class="dashboard__input-field dashboard__input-field--text" type="text" name="title"/>
            <label class="dashboard__input-label">Title</label>
        </div>
        <div class="dashboard__input-group">
            <textarea class="dashboard__input-field dashboard__input-field--textarea" name="description"></textarea>
            <label class="dashboard__input-label">Description</label>
        </div>
        <div class="dashboard__input-group">
            <div class="dashboard__attachment">
                <span id="file-list">
                    <span id="files-names"></span>
                </span>
            </div>
            <label class="dashboard__input-label">Attachment (s)</label>
        </div>
    </div>
    <div class="dashboard__divider"></div>
    <div class="dashboard__actions">
        <input type="hidden" name="process" value="create-ticket"/>
        <input class="dashboard__button dashboard__button--secondary" type="button" value="Reset"/>
        <input class="dashboard__button dashboard__button--primary" type="submit" value="Confirm"/>
        <label for="attachment">
            <a class="dashboard__button dashboard__button--primary dashboard__button--attachment" type="button">
                <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6 7.90909V16C6 19.3137 8.68629 22 12 22V22C15.3137 22 18 19.3137 18 16V6C18 3.79086 16.2091 2 14 2V2C11.7909 2 10 3.79086 10 6V15.1818C10 16.2864 10.8954 17.1818 12 17.1818V17.1818C13.1046 17.1818 14 16.2864 14 15.1818V8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                <span>Attach File</span>
            </a>
        </label>
        <input class="dashboard__attachment-file"
               type="file"
               name="attachment[]"
               accept=".jpg, .jpeg, .png, .pdf"
               id="attachment"
               multiple/>
    </div>
</form>