<?php
$permit = $this->permit;

switch ($permit['businessEntityType']) {
    case 'Sole Proprietorship':
        $permitDetails['Tax Payer\'s Details'] = [
            [
                'colspan' => 2,
                'style' => ' style="width:25%"',
                'title' => 'Last Name',
                'value' => $permit['lastName'],
            ],
            [
                'colspan' => 5,
                'style' => ' style="width:50%"',
                'title' => 'First Name',
                'value' => $permit['firstName'],
            ],
            [
                'colspan' => 1,
                'style' => ' style="width:25%"',
                'title' => 'Middle Name',
                'value' => $permit['middleName'],
            ],
        ];
        $permitDetails['Tax Payer\'s Address'][0] = [
            'colspan' => 8,
            'value' => $permit['businessAddress'],
        ];
        $permitDetails['Lessor Name'][0] = [
            'colspan' => 8,
            'value' => $permit['lessorName'],
        ];
        break;
    default:
        $permitDetails['Business Name'][0] = [
            'colspan' => 8,
            'value' => $permit['corporateName'],
        ];
        $permitDetails['Business Address'][0] = [
            'colspan' => 8,
            'value' => $permit['businessAddress'],
        ];
        break;
}

$permitDetails['Trade Name'][0] = [
    'colspan' => 8,
    'value' => $permit['tradeName'],
];
$permitDetails['Nature Of Business'][0] = [
    'colspan' => 8,
    'value' => $permit['natureOfBusiness'],
];;
$permitDetails['Others Details'] = [
    [
        'colspan' => 2,
        'style' => ' style="width:25%"',
        'title' => 'Ownership',
        'value' => $permit['businessEntityType'],
    ],
    [
        'colspan' => 2,
        'style' => ' style="width:25%"',
        'title' => 'Area (Sqm)',
        'value' => $permit['area'],
    ],
    [
        'colspan' => 2,
        'style' => ' style="width:25%"',
        'title' => 'Capital',
        'value' => $permit['capital'],
    ],
    [
        'colspan' => 2,
        'style' => ' style="width:25%"',
        'title' => 'Monthly Rent',
        'value' => $permit['monthlyRent'],
    ],
];
$subTotal = $permit['mayorsFee'] + $permit['licenseFee'] + $permit['garbageFee'] + $permit['zoningFee'];
$total = $subTotal + $permit['processingFee'];
$particulars = [
    [
        'title' => 'Mayor\'s Fee',
        'value' => $permit['mayorsFee'],
    ],
    [
        'title' => 'License Fee',
        'value' => $permit['licenseFee'],
    ],
    [
        'title' => 'Garbage Fee',
        'value' => $permit['garbageFee'],
    ],
    [
        'title' => 'Zoning Fee',
        'value' => $permit['zoningFee'],
    ],
    [
        'style' => ' style="text-align: right; border-bottom: 1px solid #000000"',
        'title' => 'Sub Total',
        'value' => $subTotal,
    ],
    [
        'style' => ' style="border-bottom: 2px solid #000000"',
        'title' => 'Processing Fee',
        'value' => $permit['processingFee'],
    ],
    [
        'style' => ' style="text-align: right; border-bottom: 5px double #000000"',
        'title' => 'Total',
        'value' => $total,
    ],
];
?>
<table class="statement-of-account__table">
    <tbody>
        <tr>
            <td colspan="7">
                <strong>REPUBLIC OF THE PHILIPPINES</strong><br/>
                CITY GOVERNMENT OF LAS PIÑAS<br/>
                Opermitcare Special Permit
            </td>
            <td colspan="1">
                Billing Date: <?= date("d M Y") ?><br/>
                Period: <?= date("Y", strtotime($permit['dateCreated'])) ?>
            </td>
        </tr>
        <tr>
            <td colspan="8">
                <div class="statement-of-account__title">Statement of Account</div>
            </td>
        </tr>
        <?php foreach ($permitDetails as $category => $columns) : ?>
            <tr>
                <td colspan="8">
                    <div class="statement-of-account__table-category"><?= $category ?></div>
                </td>
            </tr>
            <tr>
                <?php foreach ($columns as $column) :
                    $style = !empty($column['style']) ? $column['style'] : ''; ?>
                    <td colspan="<?= $column['colspan'] ?>"<?= $style; ?>>
                        <?php if (!empty($column['title'])) : ?>
                            <div class="statement-of-account__table-label"><?= $column['title'] ?></div>
                        <?php endif; ?>
                        <div class="statement-of-account__table-value"><?= $column['value'] ?></div>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="8" class="statement-of-account__table-space"></td>
        </tr>
        <tr>
            <td colspan="1" class="statement-of-account__table-summary-title">NRC</td>
            <td colspan="6" class="statement-of-account__table-summary-title">Particulars</td>
            <td colspan="1" class="statement-of-account__table-summary-title">Tax Due (PHP)</td>
        </tr>
        <?php foreach ($particulars as $particular) :
            $style = !empty($particular['style']) ? $particular['style'] : ''; ?>
            <tr>
                <td colspan="1"></td>
                <td colspan="6"
                    class="statement-of-account__table-summary-label"<?= $style; ?>><?= $particular['title']; ?></td>
                <td colspan="1" class="statement-of-account__table-summary-value"<?= $style; ?>><?= sprintf('%0.2f',
                                                                                                            $particular['value']); ?></td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td colspan="8" class="statement-of-account__table-space"></td>
        </tr>
        <tr>
            <td colspan="8">
                <div class="statement-of-account__table-label">Generated By</div>
                <div class="statement-of-account__table-value"><strong>Opermitcare</strong></div>
            </td>
        </tr>
        <tr>
            <td colspan="8" class="statement-of-account__table-space"></td>
        </tr>
        <tr>
            <td colspan="8" class="statement-of-account__table-divider"></td>
        </tr>
        <tr>
            <td colspan="8" class="statement-of-account__table-footer">
                <div class="statement-of-account__table-footer--notice">
                    <div class="statement-of-account__table-category">Notice</div>
                    <ol>
                        <li>Payment later than the quarterly deadline shall subject the taxpayer to the following:
                            <ul>
                                <li>Surcharge of twenty five percent (25%) of the total UNPAID balance on taxes, charges or
                                    fees due.
                                </li>
                                <li>Plus an interest of two percent (2%) per month of the total UNPIAD balance on taxes or
                                    charges.
                                </li>
                            </ul>
                        </li>
                        <li>Payment made thru Checks must bear the account name <strong>CITY GOVERNMENT OF LAS
                                PIÑAS</strong> only as the Payee.
                        </li>
                    </ol>
                </div>
                <div class="statement-of-account__table-footer--deadline">
                    <div class="statement-of-account__table-category">Quarterly Deadline of Payment</div>
                    <p>
                        1st Quarter - Every 20th of January<br/>
                        2nd Quarter - Every 20th of April<br/>
                        3rd Quarter - Every 20th of July<br/>
                        4th Quarter - Every 20th of October
                    </p>
                </div>
            </td>
        </tr>
    </tbody>
</table>