<div class="faq">
    <div class="faq__jumbotron">
        <div class="faq__wrapper">
            <h1>Frequently asked questions</h1>
        </div>
    </div>
    <div class="faq__section">
        <div class="faq__wrapper faq__wrapper--section">
            <div class="faq__category">
                <ul>
                    <?php foreach ($this->faq as $faq) :
                        $isActive = $faq['faqId'] < 2 ? ' active' : ''; ?>
                        <li class="js-see-content<?= $isActive ?>" data-id="<?= $faq['faqId'] ?>"><?= $faq['faqName'] ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="faq__detail">
                <?php foreach ($this->faqDetails as $faqKey => $details) : ?>
                    <?php foreach ($details['list'] as $detail) :
                        $isActive = $faqKey < 2  ? ' active' : '';
                        $detail = (array) $detail; ?>
                        <div class="faq__detail-item<?= $isActive; ?>" data-id="<?= $detail['faqId'] ?>">
                            <div class="faq__detail-title">
                                <span><?= $detail['title'] ?></span>
                                <span></span>
                            </div>
                            <div class="faq__detail-description"><?= $detail['description'] ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


