<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Portal\Service\SessionService;

$response = $this->response;
$isError = !empty($response['code']) && $response['code'] === SessionService::INVALID_CODE ? true : false;
$alertMessage = !empty($response['message']) ? $response['message'] : '';
?>

<div class="login">
    <div class="login__wrapper">
        <?php if ($isError) : ?>
            <div class="alert error">
                <?= $alertMessage ?>
                <a class="button">&times;</a>
            </div>
        <?php endif; ?>
        <div class="login__card">
            <div class="login__form">
                <h1>Login</h1>
                <p>Sign into your account</p>
                <form action="<?= $this->url('portal', ['action' => 'login']) ?>" method="post">
                    <div class="login__input">
                        <input type="text" name="username" placeholder="Username"/>
                    </div>
                    <div class="login__input">
                        <input type="password" name="password" placeholder="Password"/>
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M21.71 11.2535C20.9435 10.0884 17.2917 5 12.0002 5C6.36056 5 2.58388 10.7799 2.17695 11.4304L2.10436 11.556C1.95283 11.8611 1.96664 12.2246 2.14618 12.5195L2.29085 12.7465C3.05724 13.9116 6.70868 19 12.0002 19C17.6398 19 21.4169 13.2201 21.8235 12.5696L21.896 12.444C22.0475 12.1389 22.0338 11.7754 21.8547 11.4805L21.71 11.2535ZM4.00049 12C4.98699 10.6245 7.95149 7 11.793 7C15.4396 7 18.2962 10.2662 19.4204 11.7736L19.586 12C18.5995 13.3755 15.6345 17 11.793 17C8.14634 17 5.28978 13.7338 4.16603 12.2264L4.00049 12ZM16.0006 12C16.0006 9.7945 14.2061 8 12.0006 8C9.79512 8 8.00062 9.7945 8.00062 12C8.00062 14.2055 9.79512 16 12.0006 16C14.2061 16 16.0006 14.2055 16.0006 12ZM10.0006 12C10.0006 10.897 10.8976 10 12.0006 10C13.1036 10 14.0006 10.897 14.0006 12C14.0006 13.103 13.1036 14 12.0006 14C10.8976 14 10.0006 13.103 10.0006 12Z"></path>
                        </svg>
                    </div>
                    <div class="login__action">
                        <button type="submit">Login</button>
                    </div>
                </form>
                <div class="login__label">
                    <a href="">I forgot my password</a>
                </div>
                <div class="login__action">
                    <a href="<?= $this->url('portal', ['action' => 'sign-up']) ?>"><input type="button" value="Sign Up"/></a>
                </div>
            </div>
            <div class="login__banner"></div>
        </div>
    </div>
</div>
