<div class="support">
    <div class="support__jumbotron">
        <div class="support__wrapper">
            <h1>Support</h1>
        </div>
    </div>
    <div class="support__section">
        <div class="support__wrapper support__wrapper--section">
            <div class="support__collection">
                <div class="support__group">
                    <div class="support__video">
                        <video width="320" height="240" controls>
                            <source src="/assets/videos/sign-up.mp4" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                    </div>
                    <div class="support__description">
                        <h1>Got question?</h1>
                        <p>Click the chatbot icon on the lower left part of the screen.</p>
                    </div>
                </div>
                <div class="support__divider"></div>
                <div class="support__group">
                    <div class="support__description">
                        <h1>Special Permit</h1>
                        <p>In just a few taps, it’s easy for you to apply.</p>
                    </div>
                    <div class="support__video">
                        <video width="320" height="240" controls>
                            <source src="/assets/videos/special-permit.mp4" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                    </div>
                </div>
                <div class="support__divider"></div>
                <div class="support__group">
                    <div class="support__video">
                        <video width="320" height="240" controls>
                            <source src="/assets/videos/ticketing-tutorial.mp4" type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                    </div>
                    <div class="support__description">
                        <h1>Customer Support</h1>
                        <p>Get an overview of your inquiries with us.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>