<?php

use Application\Portal\Service\DashboardService;

$response = $this->response;
$alertClass = '';
$alertMessage = !empty($response['message']) ? $response['message'] : false;
$responseData = !empty($response['data']) ? $response['data'] : [];
$isError = null;

if (!empty($response['message'])) {
    $isError = !empty($response['code']) && $response['code'] === DashboardService::INVALID_CODE ? true : false;
    $alertClass = $isError ? ' error' : ' success';
}
?>

<div class="dashboard">
    <div class="dashboard__section">
        <div class="dashboard__wrapper">
            <div class="dashboard__side-bar">
                <h1>Dashboard</h1>
                <ul>
                    <?php foreach ($this->templates as $template) :
                        $isActive = $this->activeTab === $template['action'] ? ' active' : ''; ?>
                        <li class="dashboard__list-item<?= $isActive ?>" data-panel="<?= $template['action'] ?>">
                            <svg viewBox="0 0 25 25" version="1.1"
                                 xmlns="http://www.w3.org/2000/svg"><?= $template['icon'] ?></svg>
                            <span><?= $template['title'] ?></span>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="dashboard__content">
                <h3><?= sprintf('Hi, %s (@%s)', $this->sessionDetails['user']['firstName'], $this->sessionDetails['user']['userName']) ?></h3>
                <div class="dashboard__divider"></div>
                <?php foreach ($this->templates as $template) :
                    $isActive = $this->activeTab === $template['action'] && empty($this->activePanel) ? ' active' : '';
                    $templateName = count($template['table']) ? 'table' : 'panel'; ?>
                    <div class="dashboard__panel<?= $isActive ?>" data-panel="<?= $template['action'] ?>">
                        <?= $this->partial('partial/' . $templateName, array_merge($template, [
                            'alertClass' => $isActive ? $alertClass : '',
                            'alertMessage' => $isActive ? $alertMessage : '',
                            'responseData' => $isActive ? $responseData : [],
                        ])); ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>