<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->viewVars
?>
<div class="home">
    <div class="home__jumbotron"></div>
    <div class="home__box">
        <div class="home__wrapper">
            <div class="home__box-item">
                <div class="home__box-image home__box-image--our-home"></div>
                <div class="home__box-text">
                    <h2>Our Home</h2>
                    <p>City of Las Piñas is home to some of the best practices in locale governance.</p>
                </div>
            </div>
            <div class="home__box-item">
                <div class="home__box-image home__box-image--our-support"></div>
                <div class="home__box-text">
                    <h2>Support</h2>
                    <p>Sharing our commitment to continously enhance the experience and building lasting connections of
                        our bonafie residents.</p>
                </div>
            </div>
        </div>
    </div>
</div>
